name: prescription_decoder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  firebase_auth: ^4.19.0
  firebase_ui_auth: ^1.13.1
  firebase_core: ^2.28.0
  cupertino_icons: ^1.0.6
  modal_progress_hud_nsn: ^0.5.1
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.16.0
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
