// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtN4cow0H5Zct95vjlJf2z2dasLyJVud0',
    appId: '1:509561488660:web:e89c35138d271f2a23ae01',
    messagingSenderId: '509561488660',
    projectId: 'prescriptiondecoder-61160',
    authDomain: 'prescriptiondecoder-61160.firebaseapp.com',
    storageBucket: 'prescriptiondecoder-61160.appspot.com',
    measurementId: 'G-PY0724QW52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_JrGeumn5P8t-0r_l_qGWJaolpyIVngc',
    appId: '1:509561488660:android:9e16fdac16db4c8e23ae01',
    messagingSenderId: '509561488660',
    projectId: 'prescriptiondecoder-61160',
    storageBucket: 'prescriptiondecoder-61160.appspot.com',
  );
}
